### ISSUE TITLE
Support for Vue 2.7 and Vue 3

### ISSUE THREAD

**Issue by harrisoncramer** [ikatyang/tree-sitter-vue#20]
Does this plugin support syntax highlighting for Vue 2.7 and Vue 3?

I've noticed that opening up projects with this parser enabled, the `<template>` section doesn't seem to pick up any highlighting. Is this not supported, and if not, do you know of an alternative Vue parser that supports newer versions of Vue?

**Comment by suruaku** [comment]
![image](https://user-images.githubusercontent.com/43464534/202655628-a83f8871-1163-4481-9d30-022603c9b977.png)

I use both vue2.7 and vue3 and for me, this looks okay. I'm not sure how much the colour scheme affects colours. Maybe you have to use one that supports TS? I use [this one](https://github.com/ellisonleao/gruvbox.nvim).
