### ISSUE TITLE
Wrong highlighting int style section

### ISSUE THREAD

**Issue by timsofteng** [ikatyang/tree-sitter-vue#3]
Please take a look on screenshot. Looks like it's wrong hithlighting (it highlights `or` as operator).

![image](https://user-images.githubusercontent.com/51912173/109703508-38078c00-7b9e-11eb-8523-2a8999f2f0e1.png)

**Comment by ikatyang** [comment]
Hi, this grammar only extracts the `<style>` and similar sections where the embedded content parsing should be done in the corresponding grammar, it's probably [`tree-sitter-css`](https://github.com/tree-sitter/tree-sitter-css) in your case I guess.

![image](https://user-images.githubusercontent.com/8341033/110051525-00ad0100-7d91-11eb-8e58-3bdd2c0745f2.png)

**Comment by timsofteng** [comment]
But it is style section of vue file. You know vue file contains three sections as template, script and style.

**Comment by cloggier** [comment]
@timsofteng My understanding is that `tree-sitter-vue` *does not* provide highlighting (or any other tree-sitter functionality) for *any* of three blocks you can find in `Vue` files.

What it does is it parses file, looks for Vue top level tags, so `template`, `script` and `style`, and then *embeds* respective parsers to provide that functionality.

So for example, everything within `<style>` block will be parsed by `tree-sitter-css`, in `<template>` block it will use `tree-sitter-html`. This is called *language injection* in tree-sitter, and `tree-sitter-vue` uses that so it does not need to reinvent grammas/parsers for all possible languages Vue files can have.

What @ikatyang meant saying that it is `tree-sitter-css` in your case is that your problem has nothing to do with `tree-sitter-vue` but grammar it injected for that block, which is one from https://github.com/tree-sitter/tree-sitter-css. You should report your issue over there.

**Comment by timsofteng** [comment]
@cloggier got it!
Thanks.
I will track your issue.
